name: pokedex
description: App Flutter to list pokemons.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/pokeball.ico"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    # image_path: "assets/icon/pokeball.ico"
    background_color: "#FFDC0A2D"
    theme_color: "#FFDC0A2D"
  windows:
    generate: true
    # image_path: "assets/icon/pokeball.ico"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    # image_path: "assets/icon/pokeball.ico"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
